name: Luacheck
on: [push, pull_request]
jobs:
  Luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Update repositories
        run: sudo apt update
      - name: Install Luacheck
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: lua-check
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck linter
        run: luacheck --config .luacheckrc .